In [24]:
text1="The Vikram Sarabhai Space Centre is a space research Centre of the ISRO, focused on rocket and space vehicles"
len(text1)
words=text1.split(' ')
len(words)
type(words)
# print(text1[4:10])    Vikram
# print('z' in text1)   False
# text1.isalpha()
# text1.isalnum()
# text1.isdigit()
# text1.isdecimal()
# text1.istitle()
# text1.islower()
# ram='Ram'
# ram.istitle()
# ram.islower()
# ram.isalpha()
# ram.isalnum()

# [wordcap for wordcap in words if wordcap.istitle()]
# g1uj=[wordg for wordg in words if len(wordg)>5]

# text1=text1.casefold() - normalize like lower , more aggresive
# text1.count('S')
# text2=text1.replace('S','dd')
# text1.find('s')
# text1.rfind()
# text=text1.splitlines() - split and create list, the ones separated by newlines
# text1.index('s') 
# text1.lstrip('The') - to remove first occurance
','.join(words)


'The,Vikram,Sarabhai,Space,Centre,is,a,space,research,Centre,of,the,ISRO,,focused,on,rocket,and,space,vehicles'

In [42]:
import re

text2 = "This news article is published on month:Jan"

# matchset=re.search(r'month:\w\w\w',text2)
# if(matchset):
#     print('Found', matchset.group())
# else:
#     print('Patter not available')

text1='abcdef'

matchset=re.search(r'abcd\w',text1)
matchset.group()

matchresult=re.search(r'abc+','abcccdee') # * for >=0, + for >=1, ? for zero or one
matchresult.group()

tweet = 'I am learning #datascience and it is awesome.#python #machinelearning'

matchset1=re.findall(r'#\w+',tweet)
matchset1



['#datascience', '#python', '#machinelearning']

In [18]:
import nltk
# nltk.download()
from nltk.book import*

len(text3)
len(set(text3))
freqcount=FreqDist(text3)
vocabulary=freqcount.keys()
freqcount['The']
[word for word in vocabulary if len(word)==7 and freqcount[word]>=50]





['brought', 'because', 'brother', 'hundred', 'Pharaoh', 'Abraham']

In [32]:
import numpy
array1 = numpy.arange(1,60,3)
array2 = numpy.arange(1,80,4)

numpy.sum(array1)
numpy.cumsum(array1)
numpy.prod(array1)
numpy.cumprod(array1)
# print(numpy.union1d(array1,array2))

print(numpy.setdiff1d(array1,array2))
print(numpy.intersect1d(array1,array2))
print(array1)
print(array2)

[ 4  7 10 16 19 22 28 31 34 40 43 46 52 55 58]
[ 1 13 25 37 49]
[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58]
[ 1  5  9 13 17 21 25 29 33 37 41 45 49 53 57 61 65 69 73 77]
